- tests/lib/thrift/hello/CMakeLists.txt
Should be thrift_hello
Fixes #4
> tests: hello: correct typo thrif_hello

- .gitmodules
- lib/thrift/CMakeLists.txt
Add a git submoudle to point to upstream thrift at
https://github.com/cfriedt/thrift.git
We will be making project-specific changes in the `zephyr` branch
of that project.
The checkout corresponds with `v0.16.0`, initially.
Placed in `.upstream` for lack of a better place.
IIRC, `west` is now configured to also clone submodules by default
so the README likely does not need to be updated.
Fixes #2
> thrift: create git submodule for upstream thrift

- cmake/thrift.cmake
Use the `lib/cpp/src` subdirectory of the `.upstream` git submodule
rather than the system thrift headers.
Fixes #6
> cmake: thrift.cmake: should not include the system header path

- README.md
I thought for some reason that west automatically set
up git submodules. Maybe it's only a newer version of west
but it isn't the version that is available with pip afaik.
Fixes #30
> README: additional steps to initialize git submodule

- cmake/thrift.cmake
The pkgconfig bit was left over from earlier when the
host thrift headers were used to compile.
Fixes #52
> cmake: thrift: remove pkgconfig executable

- tests/lib/thrift/hello/src/HelloHandler.h
The `iostream` API is typically way too large to use
in Zephyr on most platforms. Use printk instead.
Fixes #29
> test: thrift: HelloHandler: do not use cout

- west.yml
The upstream PR is zephyrproject-rtos/zephyr#43987
Basing off of that so that we can roll-back the many changes like the one below in `.upstream` thrift.
```
#ifdef CONFIG_SOC_POSIX
#include <unistd.h>
#else
#include <posix/unistd.h>
#endif
```
Fixes #61
> zephyr: remove posix prefix on standard headers

- README.md
Update the documentation to include relevant details about
Thrift, Zephyr, and Google Summer of Code.
Fixes #50
Fixes #74
> readme: add links to thrift zephyr and gsoc

- samples/lib/thrift/hello_client/sample.yaml
- samples/lib/thrift/hello_server/sample.yaml
- tests/lib/thrift/hello/testcase.yaml
Currently, the build depends on https://github.com/zephyrproject-rtos/zephyr/pull/43987
That did originally include a change to allow `CONFIG_POSIX_ARCH` and `CONFIG_POSIX_API` to co-exist but the arch/posix maintainer rejected the changes.
A workaround is required until zephyrproject-rtos/zephyr#45100 is resolved.
Fixes #81
> samples + tests: disable posix arch temporarily

- scripts/pre-commit.sh
scripts: add pre-commit git hook to run clang-format
In order to increase SNR in pull requests, contributors should run:
```
cp scripts/pre-commit.sh .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
```
Then, whitespace and other common formatting issues are resolved prior to commit. Note: `.sh` files do not seem to be formatted properly by `clang-format`, so those are skipped.
Fixes #109
> scripts: add pre-commit git hook to run git-clang-format

- .github/workflows/build.yml
- samples/lib/thrift/hello_client/sample.yaml
- samples/lib/thrift/hello_client/src/main.cpp
- samples/lib/thrift/hello_server/sample.yaml
- samples/lib/thrift/hello_server/src/main.cpp
After rebasing on a more recent Zephyr release, building the samples failed with an error saying that `main()` should return an `int` rather than `void`.
Fixes #118
> samples: thrift: hello: use int main instead of void main

- .github/workflows/build.yml
- lib/thrift/src/_stat.c
- lib/thrift/src/thrift/server/TFDServer.cpp
- samples/lib/thrift/hello_client/src/main.cpp
- samples/lib/thrift/hello_server/src/main.cpp
- tests/lib/thrift/ThriftTest/src/client.cpp
- tests/lib/thrift/ThriftTest/src/main.cpp
- tests/lib/thrift/hello/src/main.cpp
- tests/lib/thrift/muzic/src/integration.c
- west.yml
Additional zephyr headers have been namespaced including ztest.h
Manual testing started failing after pull/43987/head was rebased
on main and updated.
Fixes #127
> ci: prefix zephyr headers with zephyr

- lib/thrift/Kconfig
This was left over from a previous design iteration.
> lib: thrift: Kconfig: remove nonexistent THRIFT_ZLIB

- lib/thrift/CMakeLists.txt
- west.yml
After switching to Zephyr SDK v0.15.0, we are getting some build warnings that are propogated to errors.
1. `std::iterator` was deprecated in c++17
2. `std::bind` used without including `<functional>`
The `_GLIBCXX_HAS_GTHREADS=1` define is not required until C++ threads are available.
The latter issue is fixed in .upstream
> ci: fix build error due to deprecated std::iterator

- tests/lib/thrift/ThriftTest/CMakeLists.txt
- tests/lib/thrift/hello/CMakeLists.txt
Similar to the previous fix, this is one that is necessary for the tests subdirectory. It's necessary if the library is not built prior to building tests.
> ci: fix tests build error due to deprecated std::iterator

- .github/workflows/build-posix.yml
- .github/workflows/build.yml
The two builds are independent enough that they can be separate workflows.
> ci: separate zephyr and posix builds

- .github/workflows/build-posix.yml
- .github/workflows/build.yml
- README.md
- lib/thrift/src/_stat.c
- lib/thrift/src/thrift/server/TFDServer.cpp
- samples/lib/thrift/hello_client/CMakeLists.txt
- samples/lib/thrift/hello_client/src/main.cpp
- samples/lib/thrift/hello_server/CMakeLists.txt
- samples/lib/thrift/hello_server/src/HelloHandler.h
- samples/lib/thrift/hello_server/src/main.cpp
* use `zephyr/kernel.h` since `zephyr/zephyr.h` was deprecated in zephyrproject-rtos/zephyr#49510
* samples: `hello_client` + `hello_server`: `std::iterator` fixup similar to #142 
* README: add build status badge for `build-posix.yml`
* ci: add workflow for nightly cron builds
> post-gsoc changes

- README.md
- scripts/99-thrift.yaml
Previously, when the project was structured as a downstream application, we needed to do some extra legwork to get the top-level git submodules to be pulled in, because it is not supported in west. Since then, we've switched to using submanifests, and git submodules are directly supported.
No need to manually specify submodules as west repos.
> submanifest: use built-in support for git submodules

- .github/workflows/build.yml
A huge amount of time is spent in CI updating unnecessary modules.
The TSC previously voted on a `--group-filter` option for `west update`. However, it is currently not very effective because
- `--group-filter` pulls in way too much by default
- many modules do not belong to a group
- the default is to include all modules
- it is also not possible to start a group filter subtractively (e.g. `-debug`)
Thrift only depends on 2 modules currently so simply update them individually:
- `cmsis`: all ARM targets (even qemu) require this
- `mbedtls`: required for `TSSLSocket`
> ci: only update required modules

- lib/thrift/CMakeLists.txt
- samples/lib/thrift/hello_client/CMakeLists.txt
- samples/lib/thrift/hello_server/CMakeLists.txt
- tests/lib/thrift/ThriftTest/CMakeLists.txt
- tests/lib/thrift/hello/CMakeLists.txt
- tests/lib/thrift/muzic/CMakeLists.txt
It's useful to be able to reference files relative to the root of the module. Previously, this was not working in CI because of some weird git submodule / west repo hackery.
However, since we're not using a proper submanifest and git submodule, this should work fine.
Noted, `ZEPHYR_CURRENT_MODULE_DIR` was the first choice but does not work reliably (see chre and sof workarounds). The build system automatically generates `ZEPHYR_THRIFT_MODULE_DIR` as well. If the path ever changes it does need to be modified.
> cmake: use ZEPHYR_THRIFT_MODULE_DIR
